### ISSUE TITLE
user in kubeconfig and commandline is still email address

### ISSUE THREAD

**Issue by rendhalver** [heptiolabs/gangway#125]
followup from #124 

i reconfigured our test cluster so it does not set `emailClaim` in the configmap but the user is still my email address.

This is what the commandline output looks like:
```
kubectl config set-credentials user@domain.com  \
[snip]
kubectl config set-context APP-Dev --cluster=APP-Dev --user=user@domain.com
```

The resulting kubeconfig looks the same.

**Comment by johnharris85** [comment]
There were some changes to address this (mainly #87 I think) but I think the problem is that if `emailClaim` is omitted from the config, we always fall back to setting it to `email` by default [here](https://github.com/heptiolabs/gangway/blob/34514f0a9601a9e012747c936a83a33df7d0f458/internal/config/config.go#L63) so the new logic is never _actually_ triggered. The test case misses this too because it exercises the logic but skips the creation of the defaults. I think the fix should just be to set the default e-mail value to `""` in [`config.go`](https://github.com/heptiolabs/gangway/blob/34514f0a9601a9e012747c936a83a33df7d0f458/internal/config/config.go#L63). Happy to submit a PR if we think that's the right approach. WDYT @alexbrand @stevesloka ?
